import { Patient, Doctor, Appointment, ClinicSettings, Profile, Payment, DoctorPayment, ClinicExpense, SmsLog } from '../types';
import { drMriduBase64, drSwagatBase64, drNirmalBase64 } from '../assets/images/doctors';

export const INITIAL_CLINIC_SETTINGS: ClinicSettings = {
  id: 'set-001',
  clinic_name: 'AROGYA DENTAL CARE & IMPLANT CENTRE',
  tagline: 'Multi-Speciality Aesthetic, Orthodontic & Dental Implant Clinic',
  logo_url: '',
  address: 'Pratima Medical Store, Khodasingi, Berhampur, 760001',
  phone: '+91 94370 12345',
  email: 'contact@arogyadental.com',
  website: 'https://arogyadental.com',
  gst_number: 'GSTIN21AABCA1234F1Z5',
  appointment_duration: 20,
  working_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  working_hours_start: '09:00',
  working_hours_end: '18:00',
  token_prefix: 'TK',
  token_reset_daily: true,
  footer_text: 'Please bring this prescription slip during follow-up visits. For emergency or post-treatment inquiries, please contact the reception.',
  default_registration_fee: 100,
  default_consultation_fee: 500,
  receipt_prefix: 'MR',
  sms_enabled: true,
  sms_provider: 'generic',
  created_at: '2026-01-01T08:00:00Z',
  updated_at: '2026-01-01T08:00:00Z',
};

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-001',
    doctor_code: 'DOC-001',
    name: 'Dr. Mridusmita Pathak',
    qualification: 'BDS, MDS (Orthodontics & Dentofacial Orthopedics)',
    specialization: 'Orthodontist',
    registration_number: 'DENT-REG-89214',
    mobile: '+91 94370 22001',
    email: 'dr.mridusmita@arogyadental.com',
    photo_url: drMriduBase64,
    consultation_room: 'Room 101 (Ortho Bay)',
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    start_time: '09:00',
    end_time: '17:00',
    active: true,
    created_at: '2026-01-01T08:00:00Z',
    updated_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 'doc-002',
    doctor_code: 'DOC-002',
    name: 'Dr. Swagat',
    qualification: 'BDS, MDS (Conservative Dentistry & Endodontics)',
    specialization: 'Endodontist & Dental Surgeon',
    registration_number: 'DENT-REG-54129',
    mobile: '+91 94370 22002',
    email: 'dr.swagat@arogyadental.com',
    photo_url: drSwagatBase64,
    consultation_room: 'Room 102 (Endo Suite)',
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    start_time: '09:00',
    end_time: '17:00',
    active: true,
    created_at: '2026-01-01T08:00:00Z',
    updated_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 'doc-003',
    doctor_code: 'DOC-003',
    name: 'Dr. Nirmal Chandra Mahanta',
    qualification: 'BDS, MDS (Oral & Maxillofacial Surgery, Oral Implantology)',
    specialization: 'Clinic Director & Implantologist',
    registration_number: 'DENT-REG-33108',
    mobile: '+91 94370 12345',
    email: 'dr.nirmal@arogyadental.com',
    photo_url: drNirmalBase64,
    consultation_room: 'Room 103 (Chief Surgical Implant Bay)',
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    start_time: '09:00',
    end_time: '18:00',
    active: true,
    created_at: '2026-01-01T08:00:00Z',
    updated_at: '2026-01-01T08:00:00Z',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-001',
    patient_code: 'PAT-000001',
    first_name: 'John',
    last_name: 'Doe',
    gender: 'Male',
    date_of_birth: '1991-04-12',
    age: 35,
    mobile: '9876543210',
    alternate_mobile: '9876543211',
    email: 'john.doe@example.com',
    address: '42 Highland Crest, Oakwood',
    city: 'Metro City',
    state: 'California',
    postal_code: '90210',
    emergency_contact_name: 'Mary Doe',
    emergency_contact_number: '9876543299',
    blood_group: 'O+',
    allergies: 'Penicillin allergy',
    medical_notes: 'Undergoing clear aligner treatment for lower incisor crowding.',
    active: true,
    created_by: 'user-rec-1',
    created_at: '2026-08-10T10:00:00Z',
    updated_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'pat-002',
    patient_code: 'PAT-000002',
    first_name: 'Sarah',
    last_name: 'Jenkins',
    gender: 'Female',
    date_of_birth: '1996-09-24',
    age: 29,
    mobile: '9812345678',
    email: 'sarah.j@example.com',
    address: '15 Maple Grove Way',
    city: 'Metro City',
    state: 'California',
    postal_code: '90211',
    emergency_contact_name: 'David Jenkins',
    emergency_contact_number: '9812345600',
    blood_group: 'A+',
    allergies: 'None reported',
    medical_notes: 'Root canal completed on tooth #19, reporting for crown placement.',
    active: true,
    created_by: 'user-rec-1',
    created_at: '2026-08-15T11:00:00Z',
    updated_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'pat-003',
    patient_code: 'PAT-000003',
    first_name: 'Robert',
    last_name: 'Chen',
    gender: 'Male',
    date_of_birth: '1982-11-05',
    age: 43,
    mobile: '9823456789',
    email: 'robert.chen@example.com',
    address: '77 Silicon Boulevard',
    city: 'Metro City',
    state: 'California',
    postal_code: '90214',
    emergency_contact_name: 'Grace Chen',
    emergency_contact_number: '9823456700',
    blood_group: 'B+',
    allergies: 'Sulfa drugs',
    medical_notes: 'Evaluating bridge vs implant replacement for upper right molar.',
    active: true,
    created_by: 'user-rec-1',
    created_at: '2026-08-20T09:30:00Z',
    updated_at: '2026-08-20T09:30:00Z',
  },
  {
    id: 'pat-004',
    patient_code: 'PAT-000004',
    first_name: 'Emily',
    last_name: 'Watson',
    gender: 'Female',
    date_of_birth: '2001-02-18',
    age: 25,
    mobile: '9834567890',
    email: 'emily.w@example.com',
    address: '88 Riverview Terrace',
    city: 'Metro City',
    state: 'California',
    postal_code: '90215',
    emergency_contact_name: 'Thomas Watson',
    emergency_contact_number: '9834567800',
    blood_group: 'AB+',
    allergies: 'None',
    medical_notes: 'Severe sharp pain on lower left quadrant, suspected pulpitis.',
    active: true,
    created_by: 'user-rec-1',
    created_at: '2026-09-01T14:00:00Z',
    updated_at: '2026-09-01T14:00:00Z',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-001',
    appointment_code: 'APT-000101',
    patient_id: 'pat-001',
    doctor_id: 'doc-001', // Dr. Raj Kumar
    appointment_date: '2026-09-06',
    appointment_time: '09:00',
    token_number: 1,
    appointment_type: 'Follow-up',
    reason: 'Monthly Orthodontic bracket & wire review',
    status: 'Checked-in',
    notes: 'Patient reports mild soreness in upper right premolar wire.',
    next_visit_date: '2026-10-04',
    created_by: 'user-rec-1',
    created_by_name: 'Reception Desk',
    created_at: '2026-09-01T10:00:00Z',
    updated_at: '2026-09-06T09:05:00Z',
  },
  {
    id: 'apt-002',
    appointment_code: 'APT-000102',
    patient_id: 'pat-002',
    doctor_id: 'doc-002', // Dr. Priya Sharma
    appointment_date: '2026-09-06',
    appointment_time: '09:30',
    token_number: 2,
    appointment_type: 'Procedure',
    reason: 'Final Zirconia Crown cementation tooth #19',
    status: 'Waiting',
    notes: 'Crown received from dental lab; ready for trial and fit.',
    created_by: 'user-rec-1',
    created_by_name: 'Reception Desk',
    created_at: '2026-09-02T11:30:00Z',
    updated_at: '2026-09-06T09:20:00Z',
  },
  {
    id: 'apt-003',
    appointment_code: 'APT-000103',
    patient_id: 'pat-003',
    doctor_id: 'doc-003', // Dr. Amit Rao
    appointment_date: '2026-09-06',
    appointment_time: '10:30',
    token_number: 3,
    appointment_type: 'New Consultation',
    reason: 'CBCT scan evaluation for tooth implant #14',
    status: 'Scheduled',
    notes: 'Bring previous radiographic scans.',
    created_by: 'user-rec-1',
    created_by_name: 'Reception Desk',
    created_at: '2026-09-03T14:15:00Z',
    updated_at: '2026-09-03T14:15:00Z',
  },
  {
    id: 'apt-004',
    appointment_code: 'APT-000104',
    patient_id: 'pat-004',
    doctor_id: 'doc-002', // Dr. Priya Sharma
    appointment_date: '2026-09-06',
    appointment_time: '11:15',
    token_number: 4,
    appointment_type: 'Emergency',
    reason: 'Acute pulpitis severe nocturnal pain lower left jaw',
    status: 'Scheduled',
    notes: 'Emergency slot reserved. Pulp extirpation planned.',
    created_by: 'user-rec-1',
    created_by_name: 'Reception Desk',
    created_at: '2026-09-05T16:00:00Z',
    updated_at: '2026-09-05T16:00:00Z',
  },
  // Historical appointments for patient timeline demonstration
  {
    id: 'apt-005',
    appointment_code: 'APT-000089',
    patient_id: 'pat-001',
    doctor_id: 'doc-001', // Dr. Raj Kumar
    appointment_date: '2026-08-10',
    appointment_time: '10:00',
    token_number: 5,
    appointment_type: 'New Consultation',
    reason: 'Initial orthodontic evaluation for smile alignment',
    status: 'Completed',
    notes: 'Diagnostic impressions and lateral cephalogram advised.',
    next_visit_date: '2026-09-06',
    created_by: 'user-rec-1',
    created_by_name: 'Reception Desk',
    created_at: '2026-08-01T09:00:00Z',
    updated_at: '2026-08-10T10:35:00Z',
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-rec-1',
    full_name: 'Reception Desk',
    email: 'reception@arogyadental.com',
    role: 'receptionist',
    active: true,
    created_at: '2026-01-01T08:00:00Z',
    updated_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 'user-adm-1',
    full_name: 'Dr. Nirmal Chandra Mahanta',
    email: 'dr.nirmal@arogyadental.com',
    role: 'admin',
    doctor_id: 'doc-003',
    avatar_url: drNirmalBase64,
    active: true,
    created_at: '2026-01-01T08:00:00Z',
    updated_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 'user-doc-1',
    full_name: 'Dr. Mridusmita Pathak',
    email: 'dr.mridusmita@arogyadental.com',
    role: 'doctor',
    doctor_id: 'doc-001',
    avatar_url: drMriduBase64,
    active: true,
    created_at: '2026-01-01T08:00:00Z',
    updated_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 'user-doc-2',
    full_name: 'Dr. Swagat',
    email: 'dr.swagat@arogyadental.com',
    role: 'doctor',
    doctor_id: 'doc-002',
    avatar_url: drSwagatBase64,
    active: true,
    created_at: '2026-01-01T08:00:00Z',
    updated_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 'user-doc-3',
    full_name: 'Dr. Nirmal Chandra Mahanta',
    email: 'dr.nirmal@arogyadental.com',
    role: 'doctor',
    doctor_id: 'doc-003',
    avatar_url: drNirmalBase64,
    active: true,
    created_at: '2026-01-01T08:00:00Z',
    updated_at: '2026-01-01T08:00:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    receipt_number: 'MR-000001',
    patient_id: 'pat-001',
    appointment_id: 'apt-001',
    doctor_id: 'doc-001',
    payment_type: 'CONSULTATION',
    amount: 500,
    payment_method: 'CASH',
    payment_status: 'PAID',
    notes: 'Consultation with Dr. Mridusmita Pathak',
    collected_by: 'user-rec-1',
    collected_by_name: 'Pooja Sharma (Reception)',
    collected_at: new Date().toISOString().split('T')[0] + 'T09:30:00Z',
    created_at: new Date().toISOString().split('T')[0] + 'T09:30:00Z',
    updated_at: new Date().toISOString().split('T')[0] + 'T09:30:00Z',
  },
  {
    id: 'pay-002',
    receipt_number: 'MR-000002',
    patient_id: 'pat-002',
    appointment_id: 'apt-002',
    doctor_id: 'doc-002',
    payment_type: 'CONSULTATION',
    amount: 500,
    payment_method: 'UPI',
    transaction_reference: 'UPI/2026/091104882193',
    payment_status: 'PAID',
    notes: 'Root canal follow-up consultation',
    collected_by: 'user-rec-1',
    collected_by_name: 'Pooja Sharma (Reception)',
    collected_at: new Date().toISOString().split('T')[0] + 'T10:15:00Z',
    created_at: new Date().toISOString().split('T')[0] + 'T10:15:00Z',
    updated_at: new Date().toISOString().split('T')[0] + 'T10:15:00Z',
  },
  {
    id: 'pay-003',
    receipt_number: 'MR-000003',
    patient_id: 'pat-003',
    appointment_id: 'apt-003',
    doctor_id: 'doc-003',
    payment_type: 'REGISTRATION',
    amount: 100,
    payment_method: 'CASH',
    payment_status: 'PAID',
    notes: 'One-time registration fee on enrollment',
    collected_by: 'user-rec-1',
    collected_by_name: 'Pooja Sharma (Reception)',
    collected_at: new Date().toISOString().split('T')[0] + 'T10:45:00Z',
    created_at: new Date().toISOString().split('T')[0] + 'T10:45:00Z',
    updated_at: new Date().toISOString().split('T')[0] + 'T10:45:00Z',
  },
  {
    id: 'pay-004',
    receipt_number: 'MR-000004',
    patient_id: 'pat-004',
    appointment_id: 'apt-004',
    doctor_id: 'doc-001',
    payment_type: 'PROCEDURE',
    amount: 2500,
    payment_method: 'UPI',
    transaction_reference: 'UPI/2026/984712034921',
    payment_status: 'PAID',
    notes: 'Orthodontic archwire adjustment & aligner check',
    collected_by: 'user-rec-1',
    collected_by_name: 'Pooja Sharma (Reception)',
    collected_at: new Date().toISOString().split('T')[0] + 'T11:20:00Z',
    created_at: new Date().toISOString().split('T')[0] + 'T11:20:00Z',
    updated_at: new Date().toISOString().split('T')[0] + 'T11:20:00Z',
  },
];

export const INITIAL_DOCTOR_PAYMENTS: DoctorPayment[] = [
  {
    id: 'doc-pay-001',
    doctor_id: 'doc-001',
    payment_date: new Date().toISOString().split('T')[0],
    amount: 15000,
    payment_method: 'BANK_TRANSFER',
    reference_number: 'NEFT-AXIS-20260901-4491',
    payment_period_from: '2026-08-01',
    payment_period_to: '2026-08-31',
    notes: 'August monthly consultation and procedure retainer',
    paid_by: 'user-admin-1',
    paid_by_name: 'Clinic Administrator',
    created_at: '2026-09-01T10:00:00Z',
    updated_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'doc-pay-002',
    doctor_id: 'doc-002',
    payment_date: new Date().toISOString().split('T')[0],
    amount: 12000,
    payment_method: 'UPI',
    reference_number: 'UPI/2026/DOCPAY99214',
    payment_period_from: '2026-08-01',
    payment_period_to: '2026-08-31',
    notes: 'August endodontic share disbursement',
    paid_by: 'user-admin-1',
    paid_by_name: 'Clinic Administrator',
    created_at: '2026-09-01T11:00:00Z',
    updated_at: '2026-09-01T11:00:00Z',
  },
];

export const INITIAL_CLINIC_EXPENSES: ClinicExpense[] = [
  {
    id: 'exp-001',
    expense_number: 'EXP-000001',
    expense_date: new Date().toISOString().split('T')[0],
    category: 'Gloves',
    description: 'Nitrile Examination Gloves (Box of 100, 10 boxes)',
    quantity: 10,
    unit_cost: 350,
    total_amount: 3500,
    payment_method: 'CASH',
    vendor: 'MedLife Dental Supplies',
    invoice_number: 'INV-2026-8912',
    notes: 'Restocked for Bay 1 & Bay 2',
    entered_by: 'user-rec-1',
    entered_by_name: 'Pooja Sharma (Reception)',
    created_at: new Date().toISOString().split('T')[0] + 'T09:00:00Z',
    updated_at: new Date().toISOString().split('T')[0] + 'T09:00:00Z',
  },
  {
    id: 'exp-002',
    expense_number: 'EXP-000002',
    expense_date: new Date().toISOString().split('T')[0],
    category: 'Cotton',
    description: 'Dental Cotton Rolls & Gauze Sponges',
    quantity: 5,
    unit_cost: 160,
    total_amount: 800,
    payment_method: 'CASH',
    vendor: 'Pratima Medical Store',
    invoice_number: 'PM-44812',
    notes: 'Immediate supply for sterilization wing',
    entered_by: 'user-rec-1',
    entered_by_name: 'Pooja Sharma (Reception)',
    created_at: new Date().toISOString().split('T')[0] + 'T09:15:00Z',
    updated_at: new Date().toISOString().split('T')[0] + 'T09:15:00Z',
  },
  {
    id: 'exp-003',
    expense_number: 'EXP-000003',
    expense_date: new Date().toISOString().split('T')[0],
    category: 'Dental Consumables',
    description: 'Composite Restorative Syringes (A2 & A3 Shades)',
    quantity: 4,
    unit_cost: 1200,
    total_amount: 4800,
    payment_method: 'UPI',
    vendor: '3M Dental Direct',
    invoice_number: '3M-IN-2026-092',
    notes: 'Paid via clinic UPI handle',
    entered_by: 'user-admin-1',
    entered_by_name: 'Clinic Administrator',
    created_at: new Date().toISOString().split('T')[0] + 'T10:00:00Z',
    updated_at: new Date().toISOString().split('T')[0] + 'T10:00:00Z',
  },
];

export const INITIAL_SMS_LOGS: SmsLog[] = [
  {
    id: 'sms-001',
    patient_id: 'pat-001',
    payment_id: 'pay-001',
    recipient_mobile: '9876543210',
    message_type: 'RECEIPT',
    message_body: 'Dear John Doe, thank you for your payment of ₹500 towards consultation with Dr. Mridusmita Pathak at AROGYA DENTAL CARE. Receipt No: MR-000001. Thank you.',
    sms_status: 'SENT',
    sms_sent_at: new Date().toISOString().split('T')[0] + 'T09:31:00Z',
    created_at: new Date().toISOString().split('T')[0] + 'T09:30:00Z',
  },
  {
    id: 'sms-002',
    patient_id: 'pat-003',
    recipient_mobile: '9823456789',
    message_type: 'WELCOME',
    message_body: 'Welcome to AROGYA DENTAL CARE. Dear Robert Chen, your patient registration is successfully completed. Patient ID: PAT-000003. We look forward to serving you. Thank you.',
    sms_status: 'SENT',
    sms_sent_at: new Date().toISOString().split('T')[0] + 'T10:46:00Z',
    created_at: new Date().toISOString().split('T')[0] + 'T10:45:00Z',
  },
];
